# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruktorzy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruktor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
