# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajecia', '0002_zajecia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zajecia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
