# Generated by Django 2.0.6 on 2018-06-07 22:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sample_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('action', models.CharField(choices=[('1', 'Power on'), ('0', 'Shutdown')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('ip', models.GenericIPAddressField(protocol='ipv4', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('gpu_count', models.PositiveSmallIntegerField(validators=[sample_app.models.validate_power_of_two_or_blank])),
                ('cpu_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), sample_app.models.validate_power_of_two_or_blank])),
                ('memory', models.PositiveSmallIntegerField(help_text='in gigabytes', validators=[django.core.validators.MinValueValidator(1), sample_app.models.validate_power_of_two_or_blank], verbose_name='RAM amount')),
                ('disk_space', models.PositiveSmallIntegerField(help_text='in gigabytes', validators=[django.core.validators.MinValueValidator(1), sample_app.models.validate_power_of_two_or_blank], verbose_name='Maximum available storage')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='sample_app.MachineType', to_field='slug'),
        ),
        migrations.AddField(
            model_name='command',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='sample_app.Machine'),
        ),
    ]
