# Generated by Django 2.2.1 on 2019-05-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Type')),
            ],
        ),
    ]
