# Generated by Django 2.2.1 on 2019-05-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_i_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='i_watched',
            new_name='watched',
        ),
    ]
