# Generated by Django 2.2.1 on 2019-05-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190509_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watched',
            new_name='is_watched',
        ),
    ]
