# Generated by Django 2.2.1 on 2019-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default=1.0, max_length=1000),
            preserve_default=False,
        ),
    ]
