# Generated by Django 2.2.1 on 2019-05-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(to='movie.Type'),
        ),
    ]
