# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='tag',
            field=models.CharField(max_length=160),
        ),
    ]
