# Generated by Django 2.2.1 on 2019-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphMaster', '0002_auto_20190525_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphtype',
            name='description',
            field=models.CharField(default='brak', max_length=300),
            preserve_default=False,
        ),
    ]
