# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='user name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('status', models.CharField(choices=[('e', 'Edit'), ('p', 'Published')], max_length=1, verbose_name='status')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='dislikes')),
            ],
            options={
                'ordering': ['-last_modified_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('body', models.TextField(verbose_name='body')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Article', verbose_name='article')),
            ],
            options={
                'ordering': ['body'],
            },
        ),
    ]
