# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0004_auto_20180509_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
