# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0006_auto_20180509_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisy',
            name='day_choice',
            field=models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('4', 'Piątek'), ('4', 'Sobota')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='zapisy',
            name='hour_choice',
            field=models.CharField(choices=[('1', '10:00'), ('2', '16:00'), ('3', '18:00'), ('4', '20:00')], max_length=1, null=True),
        ),
    ]
